### ISSUE TITLE
[Recipe] Stonecutter "duplicates"

### ISSUE THREAD

**Issue by Kiryonn** [NeosSkopos/ColoniesAndTechnologies#6] opened 2024-02-02 21:34 UTC
- modpack version: 39

![2024-02-02_22 26 08](https://github.com/NeosSkopos/ColoniesAndTechnologies/assets/60699390/c218c4a9-6e29-4a08-b825-3caaf90d20af)

As you can see on the image above, there are "duplicates" of a same recipe. Tho they give different amounts which makes me think it wasn't intended:
| Block | amount first | amount second |
|---|---|---|
| buttons | 4 | 32 |
| doors | 2 | 2 |
| fences | 4 | 1 |
| planks | 4 | 4 |
| pressure plates | 16 | 2 |
| signs | 3 | 2 |
| slabs | 8 | 8 |
| stairs | 4 | 5 |
| trapdoors | 4 | 3 |

**Comment by NeosSkopos** [comment] 2024-02-02 21:41
Nice find!
Adding the EMI quick craft on the left is very new, so really cool that you found this so quickly.
I'll look into this as soon as possible. :)

**Comment by NeosSkopos** [comment] 2024-02-04 17:00
Found the issue - it was caused by the 2mal3 and MasterCutter mods both adding stonecutter recipes.
Fixed with CraftTweaker scripts to remove the duplicate recipes.
Will be part of the next version update (40).

**Comment by NeosSkopos** [comment] 2024-02-05 01:08
Should now be sorted.
Version 40 is now live :)

**Closed as completed by NeosSkopos** 2024-02-05 01:08 UTC
Labels: config
